### ISSUE TITLE
popup_vat4eu_formats - no content shown

### ISSUE THREAD

**Issue by webchills** [lat9/vat4eu#20]
Zen Cart 1.5.7d

PHP 8.0.16

Template: responsive_classic

Firefox/Chrome/Edge

When clicking on the Whats this link next to the VAT ID field on the frontend registration page, the popup is opening but is completely blank. No content shown.
The content itself is there, if you look at the source code of the index.php?main_page=popup_vat4eu_formats page everything is there
No debug log as well

**Comment by lat9** [comment]
Thanks, @webchills.  I'll get this going; thanks for the report!
