### ISSUE TITLE
Major restructuring, based on a couple of zc200 PRs

### ISSUE THREAD

**Issue by lat9** [lat9/vat4eu#34]
See these two PRs for zc200; they'll require core-file overwrites for zc158a.  Needed to make the VAT Number addition to various formatted addresses less clunky:

- https://github.com/zencart/zencart/pull/6266
- https://github.com/zencart/zencart/pull/6281

**Comment by torvista** [comment]
(I don't use this.)
I know there have been discussions on adding a core tax number field, with the conclusion being I think that there was still a lot of divergence to meet the regulations in different countries in the EU.
That aside, bearing in mind Wholesale, I think more than ever the lack of any inbuilt field whatsoever for for a tax/vat id is a serious omission from the core code.

**Comment by lat9** [comment]
Once I've got all the kinks out for zc200, it's certainly a possibility for inclusion in a zc210+ release.
